services:
  # --- POSTGRESQL (Banco de Dados Principal) ---
  db:
    image: postgres:15-alpine
    container_name: ruralgest_db
    restart: always
    env_file:
      - Postgres.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # <--- ISSO SALVA DADOS!
    networks:
      - ruralgest-net
    # Healthcheck: Garante que o banco aceita conexões
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- REDIS (Cache para o Backend) ---
  redis:
    image: redis:alpine
    container_name: ruralgest_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ruralgest-net
    # Healthcheck: Garante que o Redis está respondendo PONG antes de outros usarem
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  # --- API Flask (API Restful do Backend) ---
  api:
    container_name: ruralgest_api
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - ruralgest-net
    depends_on:
      db:
        condition: service_healthy # Espera o DB estar pronto
      redis:
        condition: service_started # Espera o Redis iniciar

volumes:
  postgres_data: # Volume novo para persistir o banco

networks:
  ruralgest-net:
    driver: bridge
