version: '3.8'

services:
  # --- JENKINS (Automação) ---
  jenkins:
    build: .
    container_name: ruralgest_jenkins
    restart: unless-stopped
    # Roda como root para garantir acesso ao socket do Docker do host sem erros de permissão
    user: root 
    privileged: true
    ports:
      - "8080:8080"   # Interface Web
      - "50000:50000" # Comunicação dos Agentes
    volumes:
      # Persistência dos dados do Jenkins
      - jenkins_home:/var/jenkins_home
      # O Pulo do Gato: Permite o Jenkins criar containers usando o Docker do Debian
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Configurações Java para otimizar memória
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - ruralgest-net
    depends_on:
      - redis
      - db   

  # --- REDIS (Cache para o Backend) ---
  redis:
    image: redis:alpine
    container_name: ruralgest_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ruralgest-net

  # --- POSTGRESQL (Banco de Dados Principal) ---
  # ADICIONADO AGORA: O coração do seu sistema
  db:
    image: postgres:15-alpine
    container_name: ruralgest_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev007  # Senha 
      POSTGRES_DB: ruralgest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # <--- ISSO SALVA SEUS DADOS!
    networks:
      - ruralgest-net

volumes:
  jenkins_home:
  postgres_data: # Volume novo para persistir o banco

networks:
  ruralgest-net:
    driver: bridge
