"""Adiciona relacao usuario agricultor

Revision ID: 0088757c57ee
Revises: 5cf5a3a72367
Create Date: 2026-02-01 13:26:53.459052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0088757c57ee'
down_revision = '5cf5a3a72367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agricultor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agricultor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
