"""empty message

Revision ID: 2b389681ca2c
Revises: b33daa9e0f4c
Create Date: 2025-09-02 02:02:39.668706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b389681ca2c'
down_revision = 'b33daa9e0f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('senha', sa.String(length=255), nullable=False))
    op.drop_column('usuario', 'senha_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('senha_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('usuario', 'senha')
    # ### end Alembic commands ###
