"""nova validaçao

Revision ID: 4b8b2f3d7481
Revises: c59533fc5f28
Create Date: 2026-02-09 00:04:27.960216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8b2f3d7481'
down_revision = 'c59533fc5f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agricultor', sa.Column('comprovante_residencia', sa.String(length=50), nullable=True))
    op.drop_column('agricultor', 'numero_documento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agricultor', sa.Column('numero_documento', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('agricultor', 'comprovante_residencia')
    # ### end Alembic commands ###
