"""Inicializacao_Real

Revision ID: 5cf5a3a72367
Revises: 
Create Date: 2025-12-09 22:24:52.159159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf5a3a72367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agricultor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('comunidade', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.String(length=20), nullable=False),
    sa.Column('data_atualizacao_cadastro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_servico', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('capacidade_hectares', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('propriedade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terreno', sa.String(length=150), nullable=False),
    sa.Column('tipo_agricultura', sa.String(length=100), nullable=False),
    sa.Column('area_total', sa.Float(), nullable=False),
    sa.Column('area_exploravel', sa.Float(), nullable=False),
    sa.Column('coordenadas_geograficas', sa.String(length=50), nullable=False),
    sa.Column('agricultor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agricultor_id'], ['agricultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('data_execucao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('agricultor_id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('operador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agricultor_id'], ['agricultor.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao')
    op.drop_table('propriedade')
    op.drop_table('usuario')
    op.drop_table('servico')
    op.drop_table('agricultor')
    # ### end Alembic commands ###
