"""tabela documentos

Revision ID: 5eafa2333f32
Revises: 870f9dfcfb1f
Create Date: 2026-02-05 01:47:27.914106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eafa2333f32'
down_revision = '870f9dfcfb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('arquivo_pdf', sa.String(length=255), nullable=True),
    sa.Column('assinatura_digital', sa.String(length=255), nullable=True),
    sa.Column('data_geracao', sa.DateTime(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento')
    # ### end Alembic commands ###
