"""tabelas iniciais docker

Revision ID: 843d8adeee4f
Revises: 
Create Date: 2026-02-11 10:28:33.797570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843d8adeee4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_servico', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('capacidade_hectares', sa.Float(), nullable=True),
    sa.Column('tipo_veiculo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_servico')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agricultor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('comunidade', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.String(length=20), nullable=True),
    sa.Column('documentacao_validada', sa.Boolean(), nullable=False),
    sa.Column('comprovante_residencia', sa.String(length=50), nullable=True),
    sa.Column('data_atualizacao_cadastro', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propriedade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terreno', sa.String(length=150), nullable=False),
    sa.Column('tipo_agricultura', sa.String(length=100), nullable=False),
    sa.Column('area_total', sa.Float(), nullable=False),
    sa.Column('area_exploravel', sa.Float(), nullable=False),
    sa.Column('coordenadas_geograficas', sa.String(length=50), nullable=False),
    sa.Column('cultura_principal', sa.String(length=100), nullable=True),
    sa.Column('quantidade_gado', sa.Integer(), server_default='0', nullable=False),
    sa.Column('agricultor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agricultor_id'], ['agricultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('data_execucao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('motivo_recusa', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('agricultor_id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('operador_id', sa.Integer(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agricultor_id'], ['agricultor.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('arquivo_pdf', sa.String(length=255), nullable=True),
    sa.Column('assinatura_digital', sa.String(length=255), nullable=True),
    sa.Column('data_geracao', sa.DateTime(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_visita', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visita_tecnica')
    op.drop_table('documento')
    op.drop_table('solicitacao')
    op.drop_table('propriedade')
    op.drop_table('notificacao')
    op.drop_table('agricultor')
    op.drop_table('veiculo')
    op.drop_table('usuario')
    op.drop_table('servico')
    # ### end Alembic commands ###
