"""novas tabelas veiculo, visita tecnica e noticaçao

Revision ID: 870f9dfcfb1f
Revises: 2b389681ca2c
Create Date: 2026-02-05 00:39:17.277085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870f9dfcfb1f'
down_revision = '2b389681ca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_visita', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agricultor', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.alter_column('agricultor', 'cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('agricultor', 'contato',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_foreign_key(None, 'agricultor', 'usuario', ['usuario_id'], ['id'])
    op.add_column('propriedade', sa.Column('cultura_principal', sa.String(length=100), nullable=True))
    op.add_column( 'propriedade', sa.Column('quantidade_gado', sa.Integer(), nullable=False, server_default="0") )
    op.add_column('servico', sa.Column('tipo_veiculo', sa.String(length=50), nullable=True))
    op.alter_column('servico', 'descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'servico', ['nome_servico'])
    op.add_column('solicitacao', sa.Column('motivo_recusa', sa.String(length=255), nullable=True))
    op.add_column('solicitacao', sa.Column('veiculo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitacao', 'veiculo', ['veiculo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitacao', type_='foreignkey')
    op.drop_column('solicitacao', 'veiculo_id')
    op.drop_column('solicitacao', 'motivo_recusa')
    op.drop_constraint(None, 'servico', type_='unique')
    op.alter_column('servico', 'descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('servico', 'tipo_veiculo')
    op.drop_column('propriedade', 'quantidade_gado')
    op.drop_column('propriedade', 'cultura_principal')
    op.drop_constraint(None, 'agricultor', type_='foreignkey')
    op.alter_column('agricultor', 'contato',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('agricultor', 'cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('agricultor', 'usuario_id')
    op.drop_table('visita_tecnica')
    op.drop_table('notificacao')
    op.drop_table('veiculo')
    # ### end Alembic commands ###
