"""Adiciona tabela Propriedade

Revision ID: 9bff80a68325
Revises: 
Create Date: 2025-08-19 21:17:03.244339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bff80a68325'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propriedade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terreno', sa.String(length=100), nullable=False),
    sa.Column('tipo_agricultura', sa.String(length=100), nullable=False),
    sa.Column('area_total', sa.Float(), nullable=False),
    sa.Column('area_exploravel', sa.Float(), nullable=False),
    sa.Column('coordenadas_geograficas', sa.String(length=50), nullable=False),
    sa.Column('agricultor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agricultor_id'], ['agricultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propriedade')
    # ### end Alembic commands ###
