"""empty message

Revision ID: b33daa9e0f4c
Revises: cca6c3938e0d
Create Date: 2025-09-02 00:44:20.239703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33daa9e0f4c'
down_revision = 'cca6c3938e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agricultor', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('agricultor', 'contato',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(op.f('servico_nome_servico_key'), 'servico', type_='unique')
    op.alter_column('usuario', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'senha_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_unique_constraint(op.f('servico_nome_servico_key'), 'servico', ['nome_servico'], postgresql_nulls_not_distinct=False)
    op.alter_column('agricultor', 'contato',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('agricultor', 'cpf',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
