"""nova validaçao

Revision ID: c59533fc5f28
Revises: a82eaaea1881
Create Date: 2026-02-08 23:57:48.512628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59533fc5f28'
down_revision = 'a82eaaea1881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agricultor', sa.Column('documentacao_validada', sa.Boolean(), nullable=False))
    op.add_column('agricultor', sa.Column('numero_documento', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agricultor', 'numero_documento')
    op.drop_column('agricultor', 'documentacao_validada')
    # ### end Alembic commands ###
