"""Adiciona veiculos e notificacoes

Revision ID: df7cdde763c3
Revises: 0088757c57ee
Create Date: 2026-02-03 22:53:37.769031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7cdde763c3'
down_revision = '0088757c57ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agricultor', schema=None) as batch_op:
        batch_op.alter_column('contato',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('propriedade', schema=None) as batch_op:
        batch_op.alter_column('quantidade_gado',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['nome_servico'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('propriedade', schema=None) as batch_op:
        batch_op.alter_column('quantidade_gado',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('agricultor', schema=None) as batch_op:
        batch_op.alter_column('contato',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
