"""adiciona coluna observacoes

Revision ID: e8166415390b
Revises: f70c686aa1d0
Create Date: 2026-02-08 22:48:43.662436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8166415390b'
down_revision = 'f70c686aa1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacao', sa.Column('observacoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitacao', 'observacoes')
    # ### end Alembic commands ###
