"""ajuste datatime

Revision ID: f70c686aa1d0
Revises: 5eafa2333f32
Create Date: 2026-02-06 19:18:22.843147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f70c686aa1d0'
down_revision = '5eafa2333f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agricultor', 'data_atualizacao_cadastro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agricultor', 'data_atualizacao_cadastro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
