from .agricultor import Agricultor
from .propriedade import Propriedade
from .usuario import Usuario
from .servico import Servico
from .solicitacao import Solicitacao
from .veiculo import Veiculo
from .notificacao import Notificacao
from .visita_tecnica import VisitaTecnica
from .documento import Documento
from .auditoria import Auditoria